using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Windows.AI.MachineLearning;
using Windows.Graphics.Imaging;
using Windows.Media;
using Windows.Storage;
using MLANELib.WinML;
using TuaRua.FreSharp;
using TuaRua.FreSharp.Exceptions;
using FREObject 